"use client";

import { StoreProvider } from "./StoreProvider";
import "@/app/globals.css";

import Header from "./components/Header";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body>
          <Header/>
          {children}</body>
      </html>
    </StoreProvider>
  );
}
